if: tag IS blank # Don't build tags

dist: xenial
language: go
go:
  - "1.13"
env:
  - DOCKER_CLI_EXPERIMENTAL="enabled"
before_install:
  - git clone https://github.com/magefile/mage
  - cd mage
  - go run bootstrap.go install
  - cd -
  - rm -rf mage
jobs:
  include:
    - stage: test
      script:
        - mage -v go:test
    - stage: deploy-image
      script:
        - mage -v go:test
        - bash <(curl -s https://codecov.io/bash) -f /tmp/app.cover
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - sudo docker run --privileged linuxkit/binfmt:v0.6
        - mage -v docker:push git:push
stages:
  - name: test
    if: type = pull_request OR (type = push AND branch != master)
  - name: deploy-image
    if: type = push AND branch = master
